Basic Random based implementation of Scout robot with lumberjack avoidance
hrnr/battlecode-2017-blueteam pull request #1
Opened 2017-02-28 11:15 UTC by Lukx19

This implementation is able to collect bullets from neutral trees and avoid hitting lumberjack.

PROBLEMS:
lumberjacks and other units can make scout go to corners. The scout can be easily killed here because it takes to scout too long to find exit route by random chance.

Possible solution:
Create something like danger map with higher numbers representing more danger.

2017-02-28 13:52 UTC, hrnr requested changes
please auto-format the code. Also you might want to consider avoiding also other robots (soldiers especially) or just all enemy robots as scouts are fragile.

2017-02-28 13:52 UTC, hrnr commented on src/blueteam/Scout.java
> +	Team enemy;
we have this field in Robot.

2017-02-28 13:52 UTC, hrnr commented on src/blueteam/Scout.java
> +import java.util.Arrays;
unused import

2017-02-28 13:52 UTC, hrnr commented on src/blueteam/Scout.java
> +	Random rand;
this might want to push this to Robot too.

2017-02-28 13:52 UTC, hrnr commented on src/blueteam/Scout.java
> +	Optional<RobotInfo> nearLumberjack(){
we might want to push these to Robot too, probably make something like getNearestRobot(type, maxRadius) to make it more useful.

2017-02-28 13:52 UTC, hrnr commented on src/blueteam/Scout.java
> +	boolean moveInDir(Direction dir) throws GameActionException{
you might want to use a more sophisticated tryMove() from Robot. or we should push this to robot too.

2017-02-28 13:52 UTC, hrnr commented on src/blueteam/Scout.java
> +	ArrayList<RobotInfo> filterByType(RobotInfo[] robots, RobotType type){
this could be one liner: Arrays.stream(robots).filter(x -> x.getType() == type).collect(Collectors.toList()) 
:)

2017-03-01 08:34 UTC, Lukx19 commented
The avoidance of other robots will  be added in next round of development. This code avoids only lumberjacks because they kill me in one shot. We should develop dodging which should be used for all our robots.

2017-03-01 08:39 UTC, hrnr commented
dodging is already implemented, see #3. I'm anly wandering about lumberjacks, because you are filtering for them explicitly.

2017-03-01 08:41 UTC, Lukx19 commented on src/blueteam/Scout.java
> +	ArrayList<RobotInfo> filterByType(RobotInfo[] robots, RobotType type){
The stream doesn't work well in this framework. They take too much byte code. I had it implemented this way and I had to change it :( 
http://archive.battlecodeforum.org/2016/t/problem-using-java-streams/162/6

2017-03-01 09:48 UTC, Formicarufa approved these changes

2017-03-01 15:19 UTC, hrnr approved these changes

2017-03-01 17:32 UTC, merged