Gardener
hrnr/battlecode-2017-blueteam pull request #5
Opened 2017-03-01 16:34 UTC by exxaxxxx

Robot finds in simple way spot to plant hexagonal garden. After that he
waters the trees and is able to build other robots except tank (because
of its size).

2017-03-04 11:00 UTC, hrnr requested changes
Formatting is still not perfect, it uses BOTH tabs and spaces which may cause death to all kittens in your neighbourhood.

If you want to extend your git-fu you may want to squash all the fixup commits and remove the merge commit.

2017-03-04 11:00 UTC, hrnr commented on src/blueteam/Gardener.java
> +import battlecode.common.*;
set number of imports needed for *: 99

2017-03-04 11:00 UTC, hrnr commented on src/blueteam/Gardener.java
> +                // TODO use constants
you can use TeamConstants class to store constatnts if you wish.

2017-03-07 12:26 UTC, Lukx19 approved these changes
formating ok. Constants can be improved in next version

2017-03-07 13:23 UTC, hrnr approved these changes
it looks much better formatted.

2017-03-07 13:29 UTC, merged